# Generated by Django 3.2 on 2025-11-16 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('visible_from', models.DateField()),
                ('visible_until', models.DateField()),
                ('digital_edition', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iso_code', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('speaker', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('fosdem_url', models.TextField(null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Talk',
                'verbose_name_plural': 'Talks',
                'ordering': ['date', 'start_time', '-end_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('counter', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('fosdem_url', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('nbr_volunteers', models.IntegerField(default=0)),
                ('nbr_volunteers_min', models.IntegerField(default=0)),
                ('nbr_volunteers_max', models.IntegerField(default=0)),
                ('edition', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition')),
                ('talk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteers.talk')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['date', 'start_time', '-end_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up', models.DateField(default=datetime.date.today)),
                ('about_me', models.TextField(blank=True, verbose_name='about me')),
                ('mobile_nbr', models.CharField(blank=True, help_text="We won't share this, but we need it in case we need to contact you in a pinch during the event.", max_length=30, null=True, verbose_name='Mobile Phone')),
                ('private_staff_rating', models.IntegerField(blank=True, choices=[(0, 'No longer welcome'), (1, 'Poor'), (2, 'Not great'), (3, 'Average'), (4, 'Good'), (5, 'Superb')], null=True)),
                ('private_staff_notes', models.TextField(blank=True, null=True)),
                ('penta_account_name', models.TextField(blank=True, help_text='We need this to link your volunteers account from Pentabarf to participate in heralding/hosting a digital edition.', max_length=256, null=True, verbose_name='Your Pentabarf account name (penta.fosdem.org)')),
                ('matrix_id', models.CharField(blank=True, help_text='If you have a matrix account (mxid), you can specify it here. This is required for the virtual infodesk. The format is @username:homeserver.tld', max_length=256, null=True, verbose_name='Matrix ID')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('mugshot', models.ImageField(blank=True, null=True, upload_to='mugshots/')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.task')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'VolunteerTask',
                'verbose_name_plural': 'VolunteerTasks',
            },
        ),
        migrations.CreateModel(
            name='VolunteerTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.talk')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'VolunteerTalk',
                'verbose_name_plural': 'VolunteerTalks',
            },
        ),
        migrations.CreateModel(
            name='VolunteerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('edition', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'Volunteer Status',
                'verbose_name_plural': 'Volunteer Statuses',
            },
        ),
        migrations.CreateModel(
            name='VolunteerLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.language')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'VolunteerLanguage',
                'verbose_name_plural': 'VolunteerLanguages',
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='editions',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerStatus', to='volunteers.Edition'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='tasks',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTask', to='volunteers.Task'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('edition', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['date', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.taskcategory')),
                ('primary', models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.tasktemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTask', to='volunteers.Volunteer'),
        ),
        migrations.AddField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='volunteers.track'),
        ),
        migrations.AddField(
            model_name='talk',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTalk', to='volunteers.Volunteer'),
        ),
    ]
