# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='primary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
