# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-17 17:01


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='digital_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='penta_account_name',
            field=models.TextField(blank=True, help_text=b'We need this to link your volunteers account from Pentabarf to participate in heralding/hosting a digital edition.', max_length=256, null=True, verbose_name=b'Your Pentabarf account name (penta.fosdem.org)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Edition'),
        ),
    ]
