# Generated by Django 3.2 on 2025-11-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_emailconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
