# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-17 19:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_tasktemplate_primary'),
        ('volunteers', '0002_auto_20210117_1801'),
    ]

    operations = [
    ]
