# Generated by Django 4.2 on 2025-11-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0004_alter_edition_id_alter_emailconfirmation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="language",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="privacy",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
