# Generated by Django 2.2.18 on 2021-02-07 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_auto_20210117_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='volunteers.Track'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTalk', to='volunteers.Volunteer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.TaskTemplate'),
        ),
        migrations.AlterField(
            model_name='task',
            name='volunteers',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTask', to='volunteers.Volunteer'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volunteers.TaskCategory'),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='primary',
            field=models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='editions',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerStatus', to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='language',
            field=models.CharField(choices=[('--', 'select here'), ('en', 'English'), ('fr', 'Francais'), ('de', 'Deutsch'), ('nl', 'Nederlands'), ('es', 'Espanol')], default='en', help_text='Default language.', max_length=8, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='mobile_nbr',
            field=models.CharField(blank=True, help_text="We won't share this, but we need it in case we need to contact you in a pinch during the event.", max_length=30, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='penta_account_name',
            field=models.TextField(blank=True, help_text='We need this to link your volunteers account from Pentabarf to participate in heralding/hosting a digital edition.', max_length=256, null=True, verbose_name='Your Pentabarf account name (penta.fosdem.org)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='privacy',
            field=models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')], default='registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='private_staff_rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No longer welcome'), (1, 'Poor'), (2, 'Not great'), (3, 'Average'), (4, 'Good'), (5, 'Superb')], null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='tasks',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerTask', to='volunteers.Task'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
    ]
