# Generated by Django 2.2.26 on 2022-01-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_auto_20210207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='volunteers.Edition'),
        ),
    ]
