# Generated by Django 4.2 on 2025-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_volunteer_language_volunteer_privacy"),
    ]
    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE volunteers_volunteer
                ALTER COLUMN email_confirmed SET DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE volunteers_volunteer
                ALTER COLUMN email_confirmed DROP DEFAULT;
            """
        ),
        ]
