# Generated by Django 3.2 on 2024-01-28 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_auto_20220118_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='matrix_id',
            field=models.CharField(blank=True, help_text='If you have a matrix account (mxid), you can specify it here. This is required for the virtual infodesk. The format is @username:homeserver.tld', max_length=256, null=True, verbose_name='Matrix ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Francais'), ('de', 'Deutsch'), ('nl', 'Nederlands'), ('es', 'Espanol')], default='en', help_text='Default language.', max_length=8, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
