# Generated by Django 3.2 on 2024-02-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_auto_20240128_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='fosdem_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='fosdem_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
