# Generated by Django 3.2 on 2024-02-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_auto_20240207_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fosdem_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
