# Generated by Django 3.2 on 2025-09-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_auto_20240209_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
